### ISSUE TITLE
how to run rocksdb application by two steps and test it ?

### ISSUE THREAD

**Issue by cashey** [google/ghost-userspace#32]
sudo bazel-bin/experiments/scripts/centralized_queuing.par cfs ghost can  successfully reproduce the experiment

but i am confused with the experiment, so i want to reproduce by two step as README.md:
1. first Launch the  ghOSt scheduler(CFS or shinjuku)
2. second then  Launch  rocksdb
3. then test it ?

can you help me ? thank you very much !

**Comment by jackhumphries** [comment]
Yes, that's correct. In the ghOSt paper, we use the "PrioTable" to allow RocksDB to communicate which threads are runnable to the ghOSt scheduler, which Shinjuku supports while Linux CFS does not (I assume you are talking about the Linux CFS scheduler, not the ghOSt CFS scheduler). Alternatively, futexes can be used instead of the PrioTable (there is a `scheduler` command line option in RocksDB to toggle which mechanism to use), which CFS supports while Shinjuku does not.

For the actual commands to use and the order to run them in, `centralized_queuing.par` should print those out as it sweeps through the throughputs.
