### ISSUE TITLE
An error when moving thread to agent_shinjuku

### ISSUE THREAD

**Issue by lhpqaq** [google/ghost-userspace#35]
Sorry to trouble you again. When I run agent_shinjuku and write the user-state thread number to /sys/fs/ghost/enclave_ 1/tasks, the following error was encountered：
```
$:bazel-bin/agent_shinjuku --ncpus 2
Core map
(  0 )	(  1 )	(  2 )	(  3 )	
Initializing...
Initialization complete, ghOSt active.
PID 2517 Fatal segfault at addr 0x10: 
[0] 0x7fb0313c13c0 : __restore_rt
[1] 0x55ce4c8378a5 : ghost::BasicDispatchScheduler<>::DispatchMessage()
[2] 0x55ce4c8368c9 : ghost::ShinjukuAgent::AgentThread()
[3] 0x55ce4c83ab0a : ghost::LocalAgent::ThreadBody()
[4] 0x7fb031612de4 : (unknown)
```
When I run the agent again_shinjuku or other programs will get such errors:
```
lib/enclave.cc:452(2716) CHECK FAILED: retries < kMaxRetries [10 >= 10]
errno: 16 [Device or resource busy]
PID 2716 Backtrace:
[0] 0x55b4422162f6 : ghost::LocalEnclave::CreateAndAttachToEnclave()
[1] 0x55b442216de5 : ghost::LocalEnclave::LocalEnclave()
[2] 0x55b4421cfab1 : ghost::AgentProcess<>::AgentProcess()
[3] 0x55b4421ca9d9 : main
[4] 0x7fd96a91d0b3 : __libc_start_main
```
How to solve the first error? How can I run another program without reboot? Thank you！

**Comment by jackhumphries** [comment]
The Shinjuku scheduler expects the application it is scheduling to create a shared memory region known as the PrioTable. The PrioTable is used by the application to tell the scheduler which threads are runnable. The scheduler will crash if this region is not present. Please take a look at the RocksDB application for an example of creating and using a PrioTable.

If you are using the Shinjuku scheduler because you want support for a preemption time slice, the SOL scheduler and the centralized FIFO scheduler both support time slices now. You can set the time slice with the `--preemption_time_slice` command line argument. Neither of these two schedulers uses a PrioTable, so they will work with your application.

Regarding your second question, when an agent crashes, its enclave does not automatically get destroyed. Thus, when you launch another agent, it experiences the error you posted. You can resolve this error by destroying the enclave after an agent crash, before you launch the next agent. To destroy all enclaves on the machine, run the following command:
```
for i in /sys/fs/ghost/enclave_*/ctl; do echo destroy > $i; done
```

Please let us know if you have any other questions.

**Comment by ZhaoNeil** [comment]
> The Shinjuku scheduler expects the application it is scheduling to create a shared memory region known as the PrioTable. The PrioTable is used by the application to tell the scheduler which threads are runnable. The scheduler will crash if this region is not present. Please take a look at the RocksDB application for an example of creating and using a PrioTable.
> 
> If you are using the Shinjuku scheduler because you want support for a preemption time slice, the SOL scheduler and the centralized FIFO scheduler both support time slices now. You can set the time slice with the `--preemption_time_slice` command line argument. Neither of these two schedulers uses a PrioTable, so they will work with your application.
> 
> Regarding your second question, when an agent crashes, its enclave does not automatically get destroyed. Thus, when you launch another agent, it experiences the error you posted. You can resolve this error by destroying the enclave after an agent crash, before you launch the next agent. To destroy all enclaves on the machine, run the following command:
> 
> ```
> for i in /sys/fs/ghost/enclave_*/ctl; do echo destroy > $i; done
> ```
> 
> Please let us know if you have any other questions.



> The Shinjuku scheduler expects the application it is scheduling to create a shared memory region known as the PrioTable. The PrioTable is used by the application to tell the scheduler which threads are runnable. The scheduler will crash if this region is not present. Please take a look at the RocksDB application for an example of creating and using a PrioTable.
> 
> If you are using the Shinjuku scheduler because you want support for a preemption time slice, the SOL scheduler and the centralized FIFO scheduler both support time slices now. You can set the time slice with the `--preemption_time_slice` command line argument. Neither of these two schedulers uses a PrioTable, so they will work with your application.
> 
> Regarding your second question, when an agent crashes, its enclave does not automatically get destroyed. Thus, when you launch another agent, it experiences the error you posted. You can resolve this error by destroying the enclave after an agent crash, before you launch the next agent. To destroy all enclaves on the machine, run the following command:
> 
> ```
> for i in /sys/fs/ghost/enclave_*/ctl; do echo destroy > $i; done
> ```
> 
> Please let us know if you have any other questions.

Could you explicitly give me more information about how to create and use a PrioTable?
