### ISSUE TITLE
The ghost is support docker application as well ?

### ISSUE THREAD

**Issue by cashey** [google/ghost-userspace#43]
1.we run the docker tensorflowserving in the server pc

![image](https://github.com/google/ghost-userspace/assets/34826891/ef05bba3-4172-4eea-a736-ad03dd4f0c48)

2.we write the pid to the ghost by the command "echo PID > /sys/fs/ghost/enclave_1/tasks"

![image](https://github.com/google/ghost-userspace/assets/34826891/c3089b37-80e5-466c-932f-e141f37642e7)

3.then we run the client to test the tensorflowing  continus by the client pc 

4.we use the command "mpstat" to see whether if it is really run on the cpu 0 and 1 ,but it is not, as picture show:

![image](https://github.com/google/ghost-userspace/assets/34826891/69b1700e-437e-43d2-93d4-ab7e4545728c)

thanks very much !

**Comment by dohyunkim-dev** [comment]
Hi cashey, yes, you can schedule any user processes/threads with ghOSt. It seems to me that you are  moving only the group leaders (the threads with TID (thread ID) = 220287 and 220328 ) into ghOSt, instead of moving all the *threads* in that group. Here, "all the threads" means all the threads that are under the same `PID`s 220298 and 220328. You can verify this by seeing high %usr on all the 8 CPUs - if there were really just 2 threads, just two CPUs should be busy.

Could you check whether all the **threads** are added to the enclave? You should be able to just get all the TIDs for PID 220287 by: `ps -L --pid 220287 -o tid=`.

Hope this helps and feel free to re-open this issue if you have any follow-up.
