### ISSUE TITLE
Why is there preemption?

### ISSUE THREAD

**Issue by JaehyeongIm** [google/ghost-userspace#54]
![Image](https://github.com/user-attachments/assets/f2058fe1-3e55-4ee2-b8ee-69d299927667)
Thank you for always good answer.
This is the debugging log for simpleExp that ran one thread spin for 10ms and sleep for 10ms in the FIFO scheduler. 
But preemption occurs several times before finish work. 
Why is there preemption?

**Comment by jackhumphries** [comment]
A task preemption typically occurs because another thread in CFS (or a different higher priority scheduling class, such as the real-time classes) woke up. We have Linux give CFS tasks higher priority than ghOSt tasks, so when a CFS task wakes up, it gets strict priority over ghOSt.

Do you know if you running the ghOSt agent on a core that is busy with other things? You could use SchedViz or another tool to see which thread is causing the preemption and narrow down the debugging from there. It may just be a kworker or something similar.

**Comment by JaehyeongIm** [comment]
> A task preemption typically occurs because another thread in CFS (or a different higher priority scheduling class, such as the real-time classes) woke up. We have Linux give CFS tasks higher priority than ghOSt tasks, so when a CFS task wakes up, it gets strict priority over ghOSt.
> 
> Do you know if you running the ghOSt agent on a core that is busy with other things? You could use SchedViz or another tool to see which thread is causing the preemption and narrow down the debugging from there. It may just be a kworker or something similar.

Thank you for your kind answer. So, does this mean that on a ghOSt core, not only are ghOSt threads running, but also default Linux tasks (CFS tasks), and these CFS tasks could have higher priority, causing ghOSt tasks to be preempted? Or, is the core running both the agent and the tasks in a multithreaded manner, causing task preemption when the agent processes its work? I tried installing the testing tools, but I couldn’t complete the setup due to environment configuration issues

**Comment by jackhumphries** [comment]
Yes, there are also default Linux tasks running on those cores, which results in preemption. Take a look at these kernel params, which can help move these tasks onto other cores to avoid preemptions on the ghOSt cores: `isolcpus`, `nohz_full`, `rcu_nocbs`, and `irq_affinity`. e.g., something like the following could be helpful to you:

```
isolcpus=nohz,domain,5-6 nohz_full=5-6,rcu_nocbs=5-6,irq_affinity=0-4,7-15
```
Just be sure to replace the numbers above with the correct core numbers on your system (e.g., I assume you have a 16-core system above).

The ghOSt agents themselves could also cause preemptions, but this only happens when they forcibly wake up, such as when one agent sends an interrupt to another (via `Agent::Ping()`) or if an agent registers a timer signal handler and then the timer fires.

**Comment by JaehyeongIm** [comment]
> Yes, there are also default Linux tasks running on those cores, which results in preemption. Take a look at these kernel params, which can help move these tasks onto other cores to avoid preemptions on the ghOSt cores: `isolcpus`, `nohz_full`, `rcu_nocbs`, and `irq_affinity`. e.g., something like the following could be helpful to you:
> 
> ```
> isolcpus=nohz,domain,5-6 nohz_full=5-6,rcu_nocbs=5-6,irq_affinity=0-4,7-15
> ```
> 
> Just be sure to replace the numbers above with the correct core numbers on your system (e.g., I assume you have a 16-core system above).
> 
> The ghOSt agents themselves could also cause preemptions, but this only happens when they forcibly wake up, such as when one agent sends an interrupt to another (via `Agent::Ping()`) or if an agent registers a timer signal handler and then the timer fires.

Thank you for answer !

**Comment by JaehyeongIm** [comment]
> Yes, there are also default Linux tasks running on those cores, which results in preemption. Take a look at these kernel params, which can help move these tasks onto other cores to avoid preemptions on the ghOSt cores: `isolcpus`, `nohz_full`, `rcu_nocbs`, and `irq_affinity`. e.g., something like the following could be helpful to you:
> 
> ```
> isolcpus=nohz,domain,5-6 nohz_full=5-6,rcu_nocbs=5-6,irq_affinity=0-4,7-15
> ```
> 
> Just be sure to replace the numbers above with the correct core numbers on your system (e.g., I assume you have a 16-core system above).
> 
> The ghOSt agents themselves could also cause preemptions, but this only happens when they forcibly wake up, such as when one agent sends an interrupt to another (via `Agent::Ping()`) or if an agent registers a timer signal handler and then the timer fires.

Thank you for answer!
